# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171119_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='default.png', upload_to='treasure_images'),
        ),
    ]
